routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function(){
    return view('test');
});
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('content', 'Content\ContentController')->middleware('auth');

Route::post('customer/archived', 'Customer\CustomerController@getArchivedList')->name('customer.getArchivedList');
Route::post('customer/search', 'Customer\CustomerController@search')->name('customer.search');
Route::resource('customer', 'Customer\CustomerController')->middleware('auth');

app/Models/Content.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Content extends Model
{
    protected $guarded = [
        'id'
    ];

    protected $hidden = [
        'product_key'
    ];

}

app/Http/Controllers/Content/ContentAPIController.php
<?php

namespace App\Http\Controllers\Content;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Resources\Content as ContentResource;
use App\Models\Content;
use Carbon\Carbon;

class ContentAPIController extends Controller
{
    /**
     * @param Request $request
     * @param Content $content
     * @return ContentResource
     */
    public function content(Request $request, Content $content):ContentResource
    {
        return new ContentResource($content->find($request->id));
    }

    /**
     * @param Request $request
     * @param Content $content
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     * @throws \Exception
     */
    public function contentCollection(Request $request, Content $content):\Illuminate\Http\Resources\Json\AnonymousResourceCollection
    {
        $contents = $content->where('user_id', $request->user_id)->where('release_days', '<', $this->getElapsedDays($request))->get();
        return ContentResource::collection($contents);
    }

    /**
     * @param object $request
     * @return float
     * @throws \Exception
     */
    private function getElapsedDays(object $request):float
    {
        $elapsedSeconds = time() - (new Carbon($request->service_start_date))->getTimestamp() + $this->convertSecondsToDays($request->bonus_point);
        return ceil($elapsedSeconds / 60 / 60 / 24);
    }

    /**
     * @param $seconds
     * @return float
     */
    private function convertSecondsToDays(float $seconds):float
    {
        return ceil($seconds * 60 * 60 * 24);
    }

}

app/Http/Controllers/Content/ContentController.php
<?php

namespace App\Http\Controllers\Content;

use App\Models\Content;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Requests\ContentRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ContentController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $contents = Content::where('user_id', Auth::id())->get();
        return view('contents.index', ['contents' => $contents]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create():\Illuminate\View\View
    {
        return view('contents.create');
    }

    /**
     * @param ContentRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ContentRequest $request):\Illuminate\Http\RedirectResponse
    {
        $unixTime = Carbon::now()->getTimestamp();
        $userId = Auth::id();
        $productKey = (string)Str::uuid(); //プロダクトキーの生成

        $originalFileName = Str::of($request->file('file')->getClientOriginalName())->replace('.zip', '');
        $fileName = "{$originalFileName}_{$unixTime}.zip";
        $url = $request->file('file')->storeAs("public/contents/{$userId}", $fileName);

        $content = new Content();
        $content->fill($request->except('file'));
        $content->fill(['user_id' => $userId]);
        $content->fill(['product_key' => $productKey]);
        $content->fill(['content_url' => $url]);

        $content->save();
        return redirect(route('content.index'))->with('status', ['content' => 'コンテンツをアップロードしました', 'message_type' => 'success']);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show($id):\Illuminate\View\View
    {
        $content = Content::find($id);
        $this->authorize('view', $content);
        return view('contents.show', ['content' => $content]);
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit($id)
    {
        $content = Content::find($id);
        $this->authorize('update', $content);
        return view('contents.edit', ['content' => $content]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(ContentRequest $request, $id)
    {
        $content = Content::find($id);
        $this->authorize('update', $content);
        $content->fill($request->all())->save();
        return redirect(route('content.index'))->with('status', ['content' => 'コンテンツを更新しました', 'message_type' => 'success']);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $content = Content::find($id);
        $this->authorize('delete', $content);
        Storage::delete($content->content_url);
        $content->delete();
        return redirect(route('content.index'))->with('status', ['content' => 'コンテンツを削除しました', 'message_type' => 'success']);
    }
}

resources/views/contents/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @component('components.session_alert')
                @endcomponent
                <div class="card">
                    <div class="card-header">コンテンツのアップロード</div>

                    <div class="card-body">
                        <form action="{{ route('content.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group row">
                                <label for="content" class="col-md-4 col-form-label text-md-right">アップロードファイル</label>
                                <div class="col-md-6">
                                    <input type="file" class="form-control-file @error('file') is-invalid @enderror"
                                           id="content" name="file">
                                    @error('file')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">コンテンツ名</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control @error('name') is-invalid @enderror"
                                           id="name" name="name" value="{{ old('name') }}">
                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">コンテンツ概要</label>
                                <div class="col-md-6">
                                    <textarea class="form-control @error('description') is-invalid @enderror"
                                              id="description" name="description"
                                              rows=5>{{ old('description') }}</textarea>
                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="releaseDays" class="col-md-4 col-form-label text-md-right">解禁日数</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control @error('release_days') is-invalid @enderror"
                                           id="releaseDays" name="release_days" value="{{ old('release_days') }}">
                                    @error('release_days')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-md-4 col-form-label text-md-right"></label>
                                <div class="col-md-6">
                                    <input type="submit" class="btn btn-primary" value="送信">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contents/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    @component('components.session_alert')
                    @endcomponent
                <div class="card">
                    <div class="card-header">コンテンツ編集</div>

                    <div class="card-body">

                        <form action="{{ route('content.update', ['content' => $content->id]) }}" method="post"
                              enctype="multipart/form-data">
                            @csrf
                            @method('put')

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">コンテンツ名</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" id="name" name="name"
                                           value="{{ $content->name }}">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">コンテンツ概要</label>
                                <div class="col-md-6">
                                    <textarea class="form-control" id="description" name="description"
                                              rows=5>{{ $content->description }}</textarea>
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="releaseDays" class="col-md-4 col-form-label text-md-right">解禁日数</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" id="releaseDays" name="release_days"
                                           value="{{ $content->release_days }}">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="product_key" class="col-md-4 col-form-label text-md-right">プロダクトキー</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" id="productKey" name="product_key"
                                           value="{{ $content->product_key }}" disabled>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="content_url" class="col-md-4 col-form-label text-md-right">コンテンツURL</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" id="contentUrl" name="content_url"
                                           value="{{ $content->content_url }}" disabled>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="" class="col-md-4 col-form-label text-md-right"></label>
                                <div class="col-md-6">
                                    <input type="submit" class="btn btn-primary" value="送信">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contents/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @component('components.session_alert')
                @endcomponent
                <div class="card">
                    <div class="card-header">提供中のコンテンツ</div>

                    <div class="card-body">


                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col" style="width:25%">コンテンツ名</th>
                                <th scope="col" style="width:45%">コンテンツ概要</th>
                                <th scope="col" style="width:15%">解禁日数</th>
                                <th scope="col" style="width:15%"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($contents as $content)
                                <tr>
                                    <td>
                                        <a href="{{ route('content.show', ['content' => $content->id]) }}">{{ $content->name }}</a>
                                    </td>
                                    <td>{{ $content->description }}</td>
                                    <td>{{ $content->release_days }}</td>
                                    <td>
                                        <form action="{{ route('content.destroy', ['content' => $content->id]) }}"
                                              method="post" name="delete_content">
                                            @csrf
                                            @method('delete')
                                            <input type="submit" class="btn btn-outline-danger" value="削除"
                                                   name="delete_submit"
                                                   onclick="deleteAlert('delete_content', 'コンテンツを削除してもよろしいでしょうか？');return false">
                                            {{--                                            TODO::削除時のモーダル関数は後々別ファイルに切り出す--}}
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contents/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @component('components.session_alert')
                @endcomponent
                <div class="card">
                    <div class="card-header">コンテンツ詳細</div>

                    <div class="card-body">

                        <a href="{{ route('content.edit', ['content' => $content]) }}" class="btn btn-outline-secondary mb-3">編集する</a>

                        <table class="table">
                            <tr>
                                <th scope="col" style="width:25%">コンテンツ名</th>
                                <td>{{ $content->name }}</td>
                            </tr>
                            <tr>
                                <th scope="col" style="width:45%">コンテンツ概要</th>
                                <td>{{ $content->description }}</td>
                            </tr>
                            <tr>
                                <th scope="col" style="width:15%">解禁日数</th>
                                <td>{{ $content->release_days }} 日経過</td>
                            </tr>
                            <tr>
                                <th scope="col" style="width:15%">プロダクトキー</th>
                                <td>{{ $content->product_key }}</td>
                            </tr>
                            <tr>
                                <th scope="col" style="width:15%">コンテンツURL</th>
                                <td>{{ $content->content_url }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection