routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function(){
    return view('test');
});
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('content', 'Content\ContentController')->middleware('auth');

Route::post('customer/archived', 'Customer\CustomerController@getArchivedList')->name('customer.getArchivedList');
Route::post('customer/search', 'Customer\CustomerController@search')->name('customer.search');
Route::resource('customer', 'Customer\CustomerController')->middleware('auth');

app/Http/Controllers/Customer/CustomerController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Repositories\Customer\CustomerInterface;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\RedirectResponse;

class CustomerController extends Controller
{
    private $repository;
    private $loginUser;

    /**
     * CustomerController constructor.
     * @param CustomerInterface $repository
     */
    public function __construct(CustomerInterface $repository)
    {
        $this->repository = $repository;
        $this->middleware(function ($request, $next) {
            $this->loginUser = \Auth::user();
            return $next($request);
        });
    }

    /**
     * @param Request $request
     * @return View
     */
    public function index():View
    {
        $customers = $this->repository->all($this->loginUser->domain);
        if ($customers === ['data' => []]) return back()->with('failure', __('messages.failure', ['target' => '顧客情報の取得']));
        return view('customers.index', ['customers' => $customers]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function search(Request $request):View
    {
        $inputs = $request->all();
        $customers = $this->repository->search($inputs, $this->loginUser->domain);
        $request->session()->flash('old', $inputs);
        return view('customers.index', ['customers'=> $customers]);
    }

    /**
     * @param int $id
     * @return View
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function show(int $id):View
    {
        $customer = $this->repository->find($id, $this->loginUser->domain);
        return view('customers.show', ['customer' => $customer['data']]);
    }

    /**
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|View
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function edit(int $id):View
    {
        $customer = $this->repository->find($id, $this->loginUser->domain);
        return view('customers.edit', ['customer' => $customer['data']]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function update(Request $request):RedirectResponse
    {
        $inputs = $request->all();
        $this->repository->update($inputs, $this->loginUser->domain);
        return redirect(route('customer.show', ['customer' => $inputs['id']]))->with('success', __('messages.success', ['target' => '顧客情報の更新']));
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(int $id)
    {
        $this->repository->destroy($id, $this->loginUser->domain);
        return redirect(route('customer.index', ))->with('success', __('messages.success', ['target' => '顧客情報の削除']));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|View
     */
    public function getArchivedList()
    {
        $customers = $this->repository->getArchivedList($this->loginUser->domain);
        return view('customers.index', ['customers' => $customers, 'archived' => true]);
    }

    /**
     *
     */
    public function unarchive()
    {

    }
}

resources/views/customers/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @component('components.session_alert')
                @endcomponent
                <div class="card">
                    <div class="card-header">顧客編集</div>

                    <div class="card-body">
                        @if(is_null($customer['service_start_date']))
                        <div>
                            <form action="{{ route('customer.update', ['customer' => $customer['id']]) }}" method="post">
                                @csrf
                                @method('put')
                                <input type="hidden" class="form-control" id="id" name="id" value="{{ $customer['id'] }}">
                                <input type="hidden" class="form-control" id="serviceStartDate" name="service_start_date" value="{{ \Carbon\Carbon::now() }}">
                                <input type="submit" class="btn btn-success" value="利用開始">
                            </form>
                        </div>
                        @endif

                        <form action="{{ route('customer.update', ['customer' => $customer['id']]) }}" method="post"
                              enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            <input type="hidden" class="form-control" id="id" name="id" value="{{ $customer['id'] }}">

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">顧客名</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" id="name" name="name"
                                           value="{{ $customer['name'] }}" disabled>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="line_name" class="col-md-4 col-form-label text-md-right">LINE名</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" id="lineName" name="line_name"
                                           value="{{ $customer['line_name'] }}" disabled>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">Eメール</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" id="email" name="email" value="{{ $customer['email'] }}" disabled>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="payment" class="col-md-4 col-form-label text-md-right">お支払い方法</label>
                                <div class="col-md-6">
                                    <select class="form-control" id="payment" name="payment">
                                        <option value=0 class="form-control" @if($customer['payment'] == 0) selected @endif>クレジットカード</option>
                                        <option value=1 class="form-control" @if($customer['payment'] == 1) selected @endif>銀行振込</option>
                                        <option value=2 class="form-control" @if($customer['payment'] == 2) selected @endif>TAKETIN</option>
                                        <option value=3 class="form-control" @if($customer['payment'] == 3) selected @endif>退会済み</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="payment_status_bank" class="col-md-4 col-form-label text-md-right">お支払い状況(クレジット)</label>
                                <div class="col-md-6">
                                    <select class="form-control" id="payment_status_bank" name="payment_status_bank" disabled>
                                        <option value=1 @if($customer['payment_status_card']) selected @endif>支払済</option>
                                        <option value=0 @if(!$customer['payment_status_card']) selected @endif>未払い</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="payment_status_bank" class="col-md-4 col-form-label text-md-right">お支払い状況(銀行振込)</label>
                                <div class="col-md-6">
                                    <select class="form-control" id="payment_status_bank" name="payment_status_bank">
{{--                                        <option value=1 @if($customer['payment_status_bank']) selected @endif>支払済</option>--}}
{{--                                        <option value=0 @if(!$customer['payment_status_bank']) selected @endif>未払い</option>--}}
                                        <option value=0 @if($customer['payment_status_bank'] == 0) selected @endif>未払い</option>
                                        <option value=1 @if($customer['payment_status_bank'] == 1) selected @endif>支払済</option>
                                        <option value=2 @if($customer['payment_status_bank'] == 2) selected @endif>未払い(継続)</option>
                                        <option value=3 @if($customer['payment_status_bank'] == 3) selected @endif>前払済</option>
                                        <option value=4 @if($customer['payment_status_bank'] == 4) selected @endif>停止</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="bonus_point" class="col-md-4 col-form-label text-md-right">ボーナス</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" id="bonus_point" name="bonus_point"
                                           value="{{ $customer['bonus_point'] }}">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="marks" class="col-md-4 col-form-label text-md-right">備考欄</label>
                                <div class="col-md-6">
                                    <textarea type="text" class="form-control" id="marks" name="marks">{{ $customer['marks'] }}</textarea>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6">
                                    <input type="hidden" class="form-control" id="serviceStartDate" name="service_start_date"
                                           value="{{ $customer['service_start_date'] }}">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="" class="col-md-4 col-form-label text-md-right"></label>
                                <div class="col-md-6">
                                    <input type="submit" class="btn btn-primary" value="送信">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customers/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                @component('components.session_alert')
                @endcomponent
                <div class="card">
                    <div class="card-header">顧客一覧</div>
                    <div class="card-body">

                        @empty($archived)
                            <p>現在のアクティブ顧客数：{{ count($customers['data']) }}名</p>
                        @else
                            <p>現在のアーカイブ済み顧客数：{{ count($customers['data']) }}名</p>
                        @endempty

                        {{-- ボタンメニュー --}}

                        @empty($archived)
                            <div class="d-inline-block">
                                <form action="{{ route('customer.getArchivedList') }}" method="post">
                                    @csrf
                                    <input type="submit" class="btn btn-outline-danger" value="アーカイブ表示">
                                </form>
                            </div>
                        @else
                            <a href="{{ route('customer.index') }}" class="btn btn-outline-secondary">アクティブ顧客表示</a>
                        @endempty


                        <div class="mb-3 d-inline-block" id="buttonMenu">
                            <button type="button" class="btn btn-secondary" data-toggle="collapse"
                                    data-target="#collapseExample"
                                    aria-expanded="false" aria-controls="collapseExample">
                                検索メニュー
                            </button>
                        </div>

                        {{-- 検索メニュー --}}
                        @component('customers.partials.search')
                        @endcomponent

                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col" style="width:15%">顧客名</th>
                                <th scope="col" style="width:15%">LINE名</th>
                                <th scope="col" style="width:10%">Eメール</th>
                                <th scope="col" style="width:15%">支払方法</th>
                                <th scope="col" style="width:15%">支払状況</th>
                                <th scope="col" style="width:15%">ボーナス</th>
                                <th scope="col" style="width:15%">開始日</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($customers['data'] as $customer)
                                <tr>
                                    @empty($archived)
                                        <td>
                                            <a href="{{ route('customer.show', ['customer' => $customer['id']]) }}">{{ $customer['name'] }}</a>
                                        </td>
                                    @else
                                        <td>
                                            {{ $customer['name'] }}
                                        </td>
                                    @endempty
                                    <td>{{ $customer['line_name'] }}</td>
                                    <td>{{ $customer['email'] }}</td>
                                    {{--                                    TODO::ビューコンポーザで加工したい--}}
                                    @if($customer['payment'] == 0)
                                        <td>クレジット</td>
                                    @elseif($customer['payment'] == 1)
                                        <td>銀行振込</td>
                                    @elseif($customer['payment'] == 2)
                                        <td>TAKETIN</td>
                                    @elseif($customer['payment'] == 3)
                                        <td style="color:red">退会済み</td>
                                    @endif

                                    {{-- 銀振・カードどちらか払ってればOK出す--}}
                                    @if($customer['payment_status_bank'] == 1)
                                        <td style="color:blue;">支払済</td>
                                    @elseif($customer['payment_status_bank'] == 0)
                                        <td style="color:red;">未払い</td>
                                    @elseif($customer['payment_status_bank'] == 2)
                                        <td style="color:red;">未払い(継続)</td>
                                    @elseif($customer['payment_status_bank'] == 3)
                                        <td style="color:green;">前払済</td>
                                    @elseif($customer['payment_status_bank'] == 4)
                                        <td style="color:gray;">停止</td>
                                    @endif

                                    <td>{{ $customer['bonus_point'] }}</td>
                                    <td>@if($customer['service_start_date']) {{ (new DateTime($customer['service_start_date']))->format('Y年m月d日') }} @else
                                            待機中 @endif</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customers/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @component('components.session_alert')
                @endcomponent
                <div class="card">
                    <div class="card-header">顧客詳細</div>
                    <div class="card-body">
                        <a href="{{ route('customer.edit', ['customer' => $customer['id']]) }}"
                           class="btn btn-outline-secondary mb-3">編集する</a>
                        <div class="d-inline-block">
                            <form action="{{ route('customer.destroy', ['customer' => $customer['id']]) }}"
                                  method="post" name="archive">
                                @csrf
                                @method('delete')
                                <button class="btn btn-outline-danger ml-1 mb-3" onclick="deleteAlert('archive', '顧客をアーカイブ化してよろしいでしょうか？'); return false">アーカイブ</button>
                            </form>
                        </div>

                        <table class="table">
                            <tr>
                                <th scope="col" style="width:25%">顧客名</th>
                                <td>{{ $customer['name'] }}</td>
                            </tr>
                            <tr>
                                <th scope="col" style="width:25%">LINE名</th>
                                <td>{{ $customer['line_name'] }}</td>
                            </tr>
                            <tr>
                                <th scope="col" style="width:45%">Eメール</th>
                                <td>{{ $customer['email'] }}</td>
                            </tr>
                            <tr>
                                <th scope="col" style="width:15%">お支払い方法</th>
                                @if($customer['payment'] == 0)
                                    <td>クレジット</td>
                                @elseif($customer['payment'] == 1)
                                    <td>銀行振込</td>
                                @elseif($customer['payment'] == 2)
                                    <td>TAKETIN</td>
                                @elseif($customer['payment'] == 3)
                                    <td>退会済み</td>
                                @endif
                            </tr>
                            <tr>
                                <th scope="col" style="width:15%">お支払い状況(クレジットカード)</th>
                                @if($customer['payment_status_card'] == TRUE)
                                    <td style="color:blue;">支払済</td>
                                @elseif($customer['payment_status_card'] == FALSE)
                                    <td style="color:red;">未払い</td>
                                @endif
                            </tr>
                            <tr>
                                <th scope="col" style="width:15%">お支払い状況(銀行振込)</th>
                                @if($customer['payment_status_bank'] == 1)
                                    <td style="color:blue;">支払済</td>
                                @elseif($customer['payment_status_bank'] == 0)
                                    <td style="color:red;">未払い</td>
                                @elseif($customer['payment_status_bank'] == 2)
                                    <td style="color:red;">未払い(継続)</td>
                                @elseif($customer['payment_status_bank'] == 3)
                                    <td style="color:green;">前払済</td>
                                @elseif($customer['payment_status_bank'] == 4)
                                    <td style="color:gray;">停止</td>
                                @endif
                            </tr>
                            <tr>
                                <th scope="col" style="width:15%">ボーナスポイント</th>
                                <td>{{ $customer['bonus_point'] }}</td>
                            </tr>
                            <tr>
                                <th scope="col" style="width:15%">備考欄</th>
                                <td>{{ $customer['marks'] }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection